services:
  gateway:
    build: ./gateway
    ports:
      - 8000:8000
    depends_on:
      - user_service
      - listing_service
      - booking_service
    environment:
      USER_SERVICE_URL: user_service:8001
      LISTING_SERVICE_URL: listing_service:8002
    networks:
      - mandrosoa
  user_service:
    build: ./services/user
    ports:
      - 8001:8001
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@user_db:5432/user_service
    networks:
      - mandrosoa
  user_db:
    image: postgres:18.4-alpine
    ports:
      - 5001:5432
    volumes:
      - postgres_user_data:/var/lib/postgresql
    networks:
      - mandrosoa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 7s
      timeout: 5s
      retries: 3
  listing_service:
    build: ./services/listing
    ports:
      - 8002:8002
    depends_on:
      listing_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@listing_db:5432/listing_service
    networks:
      - mandrosoa
  listing_db:
    image: postgres:18.4-alpine
    ports:
      - 5002:5432
    volumes:
      - postgres_listing_data:/var/lib/postgresql
    networks:
      - mandrosoa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: listing_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 7s
      timeout: 5s
      retries: 3
  booking_service:
    build: ./services/booking
    ports:
      - 8003:8003
    depends_on:
      booking_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@booking_db:5432/booking_service
    networks:
      - mandrosoa
  booking_db:
    image: postgres:18.4-alpine
    ports:
      - 5003:5432
    volumes:
      - postgres_booking_data:/var/lib/postgresql
    networks:
      - mandrosoa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 7s
      timeout: 5s
      retries: 3

networks:
  mandrosoa:
    driver: bridge

volumes:
  postgres_user_data:
  postgres_listing_data:
  postgres_booking_data:
